import 'package:get/get.dart';

class MyLocal implements Translations {
  @override
  Map<String, Map<String, String>> get keys => {
    "ar": {
      "1": "جسر هيميتون",
      "2": "البحث عن دواء ",
      "3": "تصفح عن طريق الادوية",
      "4": "السعال",
      "5": "الحرارة",
      "6": "التحسس",
      "7": "وجع رأس",
      "8": " ألم الصدر",
      "9": " تعب ",
      "10": " فئة صحية ",
      "11": " قم بتحميل الوصفة الطبية الخاصة بك ",
      //login
      "12": "تسجيل دخول",
      "13": "تسجيل دخول الآن لتصفح عروضنا الساخنة ",
      "14": "إيميل ",
      "15": "كلمة السر ",
      "16": '  هل نسيت كلمة السر ؟ ',
      "17": "متابعة",
      "18": "ليس لديك حساب؟ ",
      "19": "تسجيل ",
      "20": "أو",
      // forgot
      "21": "نسيت كلمة المرور",
      "22":
      "الرجاء إدخال بريدك الإلكتروني وسنرسل لك رمز التحقق عبر البريد الإلكتروني.",
      //VerificationScreenForgetPassword
      "23": "التحقق",
      "24": "أدخل رمز التحقق الذي أرسلناه على الرقم المحدد",
      "25": "أدخل رمز التحقق",
      "26": "إعادة الإرسال",
      //PasswordScreen
      "27": "إعادة حذف كلمة المرور",
      "28":
      "أنشئ كلمة مرورك الجديدة لـ Tassy حتى تتمكن من تسجيل الدخول إلى حسابك.",
      "29": "كلمة مرور جديدة",
      "30": "تأكيد كلمة المرور",
      // OnBoarding
      "31": "مرحبًا بك في تطبيق الصيدلية لدينا",
      "32": "مرحبًا بك كصيدلاني ، نحن نقدر تجربتك و"
          "المعرفة نتطلع للعمل معكم لتقديم أفضل الخدمات"
          "لعملائنا",
      "33": "مرحبًا بكم كمدير مستودع للمستحضرات الصيدلانية"
          "، نتطلع إلى العمل معكم لتقديم أفضل المنتجات لعملائنا",
      "34": "نرحب بك كمستخدم ، ونأمل أن يكون تطبيق الصيدلية لدينا هو"
          "المكان المثالي لتلبية جميع احتياجاتك",
      "35": "المستخدم",
      "36": "المستودع",
      "37": "الصيدلي",
      //register user
      "38": "الاسم الأول",
      "39": "اسم العائلة",
      "40": "عنوان البريد الإلكتروني",
      "41": "رقم الهاتف",
      "42": "كلمة المرور",
      "43": "البيانات",
      "44": "ذكر",
      "45": "أنثى",
      "46": "دمشق",
      "47": " ريف دمشق",
      "48": "حلب",
      "49": "الرقة",
      "50": "السويداء",
      "51": "درعا",
      "52": "دير الزور",
      "53": "حماة",
      "54": "الحسكة",
      "55": "حمص",
      "56": "إدلب",
      "57": "اللاذقية",
      "58": "القنيطرة",
      "59": "طرطوس",
      "60": "عمرك",
      "61": "منطقتك",
      "62": "موقعك",
      "63": "تسجيل",
      // war
      "64": "اسم المستودع",
      "65": "رقم المستودع",
      //pharmacy
      "66": "اسم الصيدلية",
      "67": "رقم الصيدلية",
      "69": " خط الطول",
      "70": "خط العرض",
      "71": " إضافة صيدلية ",
      //
      "68": "تذكير بموعد الدواء",
      "72": "لا دواء",
      "73": "إضافة جديد",
      "74": "اسم الطب",
      "75": "الرجاء إدخال دوائك",
      "76": "الجرعة بالملغ",
      "77": "الرجاء إدخال الجرعة",
      "78": "نوع الدواء",
      "79": "حبة",
      "80": "زجاجة",
      "81": "جهاز لوحي",
      "82": "حقنة",
      "83": "تأكيد",
      "84": "الرجاء إدخال اسم الدواء",
      "85": "اسم الطب موجود بالفعل",
      "86": "الرجاء إدخال الجرعة المطلوبة",
      "87": "الرجاء تحديد فترة التذكير",
      "88": "الرجاء تحديد وقت بدء التذكير",
      "89": "تذكير:",
      "90": "حان وقت أخذك",
      "91": "حسب الجدول الزمني",
      "92": "حان وقت تناول دوائك حسب الجدول الزمني",
      "93": "وقت البدء",
      "94": "تذكيري كل",
      "95": "حدد فاصل زمني",
      "96": "ساعة",
      "97": "ساعات",
      "98": "كل",
      "99": "تفاصيل",
      "100": "حذف",
      "101": "حذف هذا التذكير؟",
      "102": "إلغاء",
      "103": "حسنًا",
      "104": "اسم الطب",
      "105": "الجرعة",
      "106": "غير محدد",
      "107": "ملغ",
      "108": "نوع الدواء",
      "109": "لا شيء",
      "110": "غير محدد",
      "111": "فاصل الجرعة",
      "112": "ساعة |",
      "113": "ساعات |",
      "114": "مرة واحدة في اليوم",
      "115": "وقت في اليوم",
      "116": "وقت البدء",
      "117": "مليسه",
      "118": "البابونج",
      "119": "زهور",
      "120": "حمى",
      "121": "نعنع",
      "122": "قرفة",
      "123": "شاي",
      "124": "لافاندر",
      "125": "باسل",
      "126": "الزنجبيل",
      "127": "الزعفران",
      "128": "حلبة",
      "129": "باسل",
      "130": "عرق السوس",
      "131": "كركم",
      "132": "أشواغاندا",
      "133": "ليمون",
      "200": "اضافه موظف",
      "201": "اضافه موزع",
      "202": "ايميل الموظف",
      "203": "ايميل موزع",
      '300': 'صيدلياتي',
      "301": 'في انتظار التحقق',
      '302': 'محقق',
      '303': 'اسم الصيدلية',
      '304': 'الرقم',
      '305': 'انشاء طلبية',
      '306': 'من أي مستودع',
      '307': 'أدويتي',
      '308': 'من أجل البحث أو التحديث',
      '309': 'اظهار المستودعات',
      '311': 'اظهار المستودعات التي بالتطبيق',
      '312': 'صيدلية',
      '313': 'اسم المستودع',
      '314': 'تاريخ الطلبية',
      '315': 'التالي',
      '316': 'طلبية الادوية',
      '317': 'من أدوية المستودع',
      '318': 'اختار نوع الطلبية',
      //drawer
      '319': 'الرئيسية',
      '320': 'طلبياتي',
      '321': 'وصفتي الطبية',
      '322': 'تذكير بموعد الدواء',
      '323': 'صيدلياتي',
      '324': 'مستودعاتي',
      '325': 'اللغة',
      '326': 'إضافة صيدلية',
      '327': 'إضافة مستودع',
      '328': 'تسجيل خروج',
      //InvoicesDetails
      '329': 'تأكيد الدفع',
      '330': 'اسم الدواء',
      '331': 'السعر الكلية',
      '332': 'الكمية',
      '333': 'الوصف بالانكليزي',
      '334': "الوصف بالعربي",
      '335': 'السعر التجاري',
      '336': 'السعر الصافي',
      //InvoicesOrder
      '337': 'فواتيري',
      '338': 'لا يةجد فواتير',
      '339': 'صيدلية',
      '340': 'رقم',
      '341':'تاريخ الطلبية',
      '342':'تفاصيل الطلبية',
      //mid
      '343':'طلبياتي',
      '344':'التالي',
      '345':'اسم الشركة',
      '346':'السعر الصافي',
      '347':'السعر التجاري',
      '348':'الحد الأقصى للكمية',
      '349':'الكمية',
      '350':'العرض',
      '351':'الكمية المطلوبة',
      '352':'الكمية المجانية',
      "353":'الدواء',
      //search
      '354':'البحث',
      '355':'البحث عن دواء',
      '356':'الذهاب للتحديث',
      //show order
      '357':'إرسال',
      '358':'مجاني',
      '359':'تحميل',
      '360':'إزالة',
      '361':'تحديث',
      //warehouse button
      '362':'إضافة موظف',
      '363':'أدخل الايميل الخاص بك',
      '364':'إضافة',
      '365':'إضافة موظف أو موزع',
      '367':'للبحث والتحديث',
      '368':'عرض الطلبات وإنشاء فاتورة',
      '369':'اختار الموزع',
      '370':'إنشاء فاتورة',
      '371':'لوحة تحكم',
      '372':'اضافي',
      '373':'إضافة طلب',
      '374':'حذف طلب',
      '375':'الاسم',
      '376':'الوصف',
      '377':'انشاء qr',
      '378':'التحقق من وصول الطلب',
      '379':'اضافة مستودع جديد',
      "380":'اذن لفتح صيدلية',
      '381':'اضافة مستودع',
      '382':'اسم المستودع',
      '383':'رقم المستودع',
      '384':'اذن لفتح مستودع'

    },
    "en": {
      "1": "Hemiton Bridge",
      "2": "Search Medicine",
      "3": "Browse by pharma",
      "4": "Cough",
      "5": "Fever",
      "6": "Skin Care",
      "7": "Headache",
      "8": " Pain Relief",
      "9": " Weakness",
      "10": " Health Category",
      "11": " Upload your prescription",
      // login
      "12": "Login",
      "13": " login now to browse our hot offers",
      "14": "email",
      "15": "password",
      "16": '  Forget password ?',
      "17": "Continue",
      "18": "don\'t  have an account ?",
      "19": "Register",
      "20": "OR",
      // forgot
      "21": "Forgot Password",
      "22":
      "Please enter your email and we will emil you a verification code.",
      //VerificationScreenForgetPassword
      "23": "Verification",
      "24": "Enter verification code we've sent on given number",
      "25": "Enter Verification Code",
      "26": "Resend",
      //PasswordScreen
      "27": "Resete Password",
      "28":
      "Create your new password for Tassy so you can login to your account.",
      "29": "New password",
      "30": "Confirm password",
      //OnBoarding
      "31": "Welcome to our pharmacy app",
      "32": "welcome as pharmacist,we value your experience and"
          " knowledge we look forward to working with you to provide the best services"
          " to our customers",
      "33": "welcome as a warehouse manager for pharmaceuticals"
          ",we look forward to working with you to provide the best products to our customers",
      "34":
      "welcome you as a user ,We hope that our pharmacy app will be the "
          "perfect place to meet all your needs",
      "35": "User           ",
      "36": "Warehouse",
      "37": "Pharmacy",
      // register user
      "38": "First Name",
      "39": "Last Name",
      "40": "Email Address",
      "41": "Phone Number",
      "42": "password",
      "43": "data",
      "44": "Male",
      "45": "Female",
      "46": "Damascus",
      "47": "Rif Dimashq",
      "48": "Aleppo",
      "49": "Raqqa",
      "50": "Al-Suwayda",
      "51": "Daraa",
      "52": "Deir ez-Zor",
      "53": "Hama",
      "54": "Al-Hasakah",
      "55": "Homs",
      "56": "Idlib",
      "57": "Latakia",
      "58": "Quneitra",
      "59": "Tartus",
      "60": "Your Age",
      "61": "Your Area",
      "62": "Your Location",
      "63": "register",
      //warehous
      "64": "Warehouse Name",
      "65": "Warehouse Number",
      //pharmacy
      "66": "pharmacy Name",
      "67": "pharmacy Number",
      "69": "longitude",
      "70": "latitude",
      "71": "Add Pharmacy",
      // pill reminder
      "68": "Pill Reminder",
      "72": "No Medicine",
      "73": "Add New",
      "74": "Medicine Name",
      "75": "Please enter your medicine",
      "76": "Dosage in mg",
      "77": "Please enter the dosage",
      "78": " Medicine Type",
      "79": "pill",
      "80": "bottle",
      "81": "tablet",
      "82": "syringe",
      "83": "Confirm",
      "84": "please enter the medicine name",
      "85": "Medicine name already exists",
      "86": "please enter the dosage required",
      "87": "please select the reminder interval",
      "88": "please select the reminder starting time",
      "89": "Reminder:",
      "90": "It is time to take your ",
      "91": ",according to schedule",
      "92": "It is time to take your medicine, according to schedule",
      "93": " Starting Time",
      "94": "Remind me every",
      "95": "Select an Interval",
      "96": "hour",
      "97": "hours",
      "98": "Every",
      "99": "Details",
      "100": "Delete",
      "101": "Delete This Reminder ?",
      "102": "Cancel",
      "103": "Ok",
      "104": "Medicine Name",
      "105": "Dosage",
      "106": "No Specified",
      "107": "mg",
      "108": "Medicine Type",
      "109": "none",
      "110": "Not Specified",
      "111": "Dose Interval",
      "112": " hour | ",
      "113": " hours |",
      "114": "One time a day",
      "115": "time a day",
      "116": "Start Time",
      "117": "Malisa",
      "118": "Chamomile",
      "119": "Flowers",
      "120": "Fever",
      "121": "Mint",
      "122": "Cinnamon",
      "123": "Tea",
      "124": "Lavander",
      "125": "Basil",
      "126": "Ginger",
      "127": "Saffron",
      "128": "Fenugreek",
      "129": "Basil",
      "130": "Liquorice",
      "131": "Curcum",
      "132": "Ashwagandha",
      "133": "Lemon",
      "200": "Add Employee",
      "201": "Add Dispenser",
      "202": "Employee Email",
      "203": "Dispenser Email",
      "300": 'My Pharmacy',
      '301': 'Waiting for verification',
      '302': 'validated',
      '303': 'Pharmacy',
      '304': 'Number',
      '305': 'Make Order',
      '306': 'From any warehouse',
      '307': 'My Medicine',
      '308': 'for searsh or update',
      '309': 'Show warehouse',
      '311': 'show order and create invoices',
      '312': 'Pharmacy',
      '313': 'Warehouse Name',
      '314': 'Order Date',
      '315': 'Next',
      '316': 'Order medicine',
      '317': 'from warehouse medicine',
      '318': 'Choose the type of order',
      //drawer
      '319': 'Home',
      '320': 'My Order',
      '321': 'My Prescription',
      '322': 'Pill Reminder',
      '323': 'My Pharmacy',
      '324': 'My Warehouse',
      '325': 'Language',
      '326': 'Add Pharmacy',
      '327': 'Add warehouse',
      '328': 'Logout',
      //InvoicesDetails
      '329': 'ConfirmPayment',
      '330': 'Medicine Name',
      '331': 'Total Price',
      '332': 'Quantity',
      '333': 'Description_en',
      '334': 'Description_ar',
      '335': 'Commercial price',
      '336': 'Net price',
      //InvoicesOrdershow
      '337': 'My Invoices',
      '338': 'There are no Invoices',
      '339': 'Pharmacy',
      '340': 'Number',
      '341':'Order Date',
      '342':'Invoices details',
      //mid
      '343':'My Order',
      '344':'next',
      '345':'Company name',
      '346':'Net Price',
      '347':'Commercial Price',
      '348':'Max Quantity',
      '349':'Quantity',
      '350':'Offers',
      '351':'DemandQuantity',
      '352':'FreeQuantity',
      "353":'Medicine',
      //search
      '354':'Search',
      '355':'Search for medicine',
      '356':'Go to update',
      //show order
      '357':'send',
      '358':'free',
      '359':'load',
      '360':'remove',
      '361':'update',
      //warehouse button
      '362':'Add Employee',
      '363':'Enter the email',
      '364':'Add',
      '365':'add employee or dispenser',
      '367':'for search or update',
      '368':'show order and create invoices',
      '369':'Choose the Dispensers',
      '370':'create Invoices',
      '371':'Dashboard',
      "372":'Additional',
      '373':'add order',
      '374':'remove order',
      '375':'Name',
      '376':'Description',
      '377':'Create Qr',
      '378':'in order to check the arrival of order',
      '379':'Add New Warehouse',
      '380':'Permission to open the pharmacy',
      '381':'Add Warehouse',
  '382':'Warehouse Name',
  '383':'Warehouse Number',
  '384':'Permission to open the warehouse'


    }
  };
}
